### ISSUE TITLE
现在仙林这边三网合一了，应该是不同的运营商有不同的标识符。
宿舍的认证网页ip好像是1.1.1.1，192.168.168.168只能用在njupt上

### ISSUE THREAD

**Issue by decentone** [kaijianyi/NJUPT_NET#1]

**Comment by kaijianyi** [comment]
你好，我们这边宿舍还没有改造，目前没有条件，等一段时间我会更新的。

**Comment by kaijianyi** [comment]
> _No description provided._

你好，我们这边宿舍还没有改造，目前没有条件，等一段时间我会更新的。

**Comment by kaijianyi** [comment]
> _No description provided._

你好，我们这边宿舍还没有改造，目前没有条件，等一段时间我会更新的。
